подключил main.js и добавил 2 функции
htmlacademy-javascript/1963923-kekstagram-25 pull request #2
Opened 2022-02-20 11:45 UTC by SEN1974

2022-02-20 15:03 UTC, 4err requested changes
Изменять форматирование html кода нельзя. Верни все обратно.

2022-02-20 15:03 UTC, 4err commented on js/main.js
> +}
Нужно добавить обработку ситуаций, если передадут отрицательные значения. По условию, функция не должна их принимать.

2022-02-20 20:36 UTC, SEN1974 commented
В HTML коде форматирование я не изменял вручную, я только подключил main.js. Форматирование произошло автоматически.

2022-02-21 04:48 UTC, 4err commented
> В HTML коде форматирование я не изменял вручную, я только подключил main.js. Форматирование произошло автоматически.

Ага, это сделал твой редактор, по своим настройкам. Так происходить не должно. Нужно отключить автоформатирование и скачать код из мастер репозитория, чтобы он остался в том виде, котором был. Ты как разработчик не должен вмешиваться в работу других частей проекта. В данном случае в разметку.

2022-02-21 06:42 UTC, SEN1974 commented
И как отключить автоформатирование?

2022-02-21 14:06 UTC, merged